name: todo-app
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    depends_on:
      - backend
      - frontend
  frontend:
    image: miroslav19/farm_stack:front
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    expose:
      - "3000"
    command: "npm start"
  backend:
    image: miroslav19/farm_stack:back
    build: ./backend

    expose:
      - "3001"
    environment:
      - DEBUG=true
    env_file:
      - path: ./.env
        required: true

